In [95]:
import numpy as np

#Problem 1

#1
a = np.zeros((2, 2))
print(a)

#2
brr = np.ones((4,2))
print(brr)

#3
crr = np.full((4,4),2)
print(crr)

#4
drr = np.zeros_like(a)
print(drr)

#5
err = np.ones_like(b)
print(err)

#6
new_list = [1,2,3,4]
f = np.array(new_list)
print(f)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4]


In [96]:
#Problem 2

#1
grr= np.arange(10,50)
print(grr)

#2
hrr= np.arange(0,9)

matrix = hrr.reshape(3,3)
print(matrix)

#3
irr = np.eye(3)
print(irr)

#4
jrr = np.random.random(30)
print(jrr)
mean = jrr.mean()
print(mean)

#5
krr = np.random.random((10,10))
print(krr)
print("Max Value", krr.max())
print("Min Value", krr.min())



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.62561413 0.98192323 0.58641185 0.9277634  0.5113367  0.05480956
 0.05448552 0.49556179 0.97883551 0.02213127 0.74974209 0.92936439
 0.2181133  0.65860351 0.64867294 0.8561968  0.6569282  0.76360693
 0.73785398 0.04579506 0.49210233 0.51077849 0.63333791 0.91120379
 0.89502075 0.96922957 0.22091292 0.3827846  0.56729454 0.36676187]
0.5817725649461568
[[0.60239982 0.96068553 0.47381689 0.41480431 0.10573072 0.19006608
  0.13468434 0.12837867 0.0769625  0.5007239 ]
 [0.64563815 0.38435473 0.92353748 0.95102243 0.41894001 0.17456861
  0.54446328 0.39736556 0.47499318 0.23429745]
 [0.79107606 0.530331   0.3967225  0.67139794 0.20112476 0.09608801
  0.76185333 0.39220559 0.9988828  0.45819565]
 [0.70417758 0.72562165 0.82288726 0.04937406 0.52858728 0.80190091
  0.157183   0.93377405 0.16705964 0.1740327

In [97]:
#6
lrr = np.zeros(10)
print(lrr)
lrr[4] = 1
print(lrr)

#7
arr = [1,2,0,0,4,0]
arr_np = np.array(arr)
print(arr_np)
reversed = np.flip(arr_np)
print(reversed)

#8
mrr = np.zeros((5,5), dtype=int)
mrr[0, :]= 1 #top row
mrr[-1, :]= 1 #bottom row
mrr[:, 0]= 1  #left column
mrr[:, -1]= 1 #right column
print(mrr)

#9
nrr= np.zeros((8,8), dtype=int)
nrr[1::2, ::2] = 1 #row: 1,3,5,7 column: 0,2,4,6
nrr[::2, 1::2] = 1#row 0,2,4,6 column: 1,3,5,7
print(nrr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1 2 0 0 4 0]
[0 4 0 0 2 1]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [78]:
#Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

add_1= x + y
add_2 = v + w
print(add_1)
print(add_2)

sub_1 = x - y
sub_2 = v - w
print(sub_1)
print(sub_2)

multiplication = x * 2
multiplication_1 = w * 9
print(multiplication)
print(multiplication_1)

x_square = x ** 2
print(x_square)
y_square = y ** 2
print(y_square)
v_square = v ** 2
print(v_square)
w_square = w ** 2
print(w_square)

V_W = np.dot(v, w)
print("Dot Product between v and w",V_W)

X_Y = np.dot(x, y)
print("Dot Product between x and y \n", X_Y)

row_concat = np.concatenate((x,y), axis=0)
print(row_concat)

column_concat = np.vstack((v,w))
print(column_concat)

# concat_xv = np.concatenate((x,v), axis=0)
# print(concat_xv)
#all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
[[ 2  4]
 [ 6 10]]
[ 99 108]
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
Dot Product between v and w 219
Dot Product between x and y 
 [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [79]:
#Problem 4

#1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

I = np.eye(2, dtype=int)

A_inv = np.linalg.inv(A)
AdotA_inv = np.dot(A, A_inv)

AdotA_inv_int = np.round(AdotA_inv).astype(int)
print(AdotA_inv_int)

if np.array_equal(AdotA_inv_int, I):
    print("True")
else:
    print(False)

#2
AdotB = np.dot(A,B)
BdotA = np.dot(B,A)

print(AdotB)
print(BdotA)

if np.array_equal(AdotB, BdotA):
    print("Equal")
else:
    print("Not Equal")


#3
AdotB = np.dot(A,B)
AdotB_T = AdotB.T

B_T = B.T
A_T = A.T
B_TdotA_T = np.dot(B_T, A_T)

if np.array_equal(AdotB_T, B_TdotA_T):
    print("Equal: (AB)^T = B^T A^T")
else:
    print("NotEqual")
    


[[1 0]
 [0 1]]
True
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Not Equal
Equal: (AB)^T = B^T A^T


In [ ]:
#Linear Equations
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([[-1],[-3],[9]])

Ainv = np.linalg.inv(A)
x = np.dot(Ainv, B)

print(x)

[[ 2.]
 [ 1.]
 [-2.]]


In [ ]:
#Element-Wise Addition

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(n)]
end_time = time.time()
print("Time taken for Python list addition:", end_time - start_time, "seconds")

arr1 = np.array(n)
arr2 = np.array(n)

start_time = time.time()
arr_sum = arr1 + arr2
end_time = time.time()
print("Time taken for NumPy array addition:", end_time - start_time, "seconds")


Time taken for Python list addition: 0.005380868911743164 seconds
Time taken for NumPy array addition: 7.772445678710938e-05 seconds


In [91]:
#Element wise Multiplication

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(n)]
end_time = time.time()
print("Time taken for Python list multiplication:", end_time - start_time, "seconds")

arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
arr_product = arr1 * arr2
end_time = time.time()
print("Time taken for NumPy array multiplication:", end_time - start_time, "seconds")


Time taken for Python list multiplication: 0.007099151611328125 seconds
Time taken for NumPy array multiplication: 0.0002689361572265625 seconds


In [ ]:
#Dot Product

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(n))
end_time = time.time()
print("Time taken for Python list dot product:", end_time - start_time, "seconds")

arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
dot_arr = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for NumPy array dot product:", end_time - start_time, "seconds")


Time taken for Python list dot product: 0.005666017532348633 seconds
Time taken for NumPy array dot product: 0.0011010169982910156 seconds


In [94]:
import time
import numpy as np
import random

n = 1000

matrix1 = [[random.randint(0,10) for i in range(n)] for i in range(n)]
matrix2 = [[random.randint(0,10) for i in range(n)] for i in range(n)]

start_time = time.time()

result_list = [[0]*n for i in range(n)]

for i in range(n):
    for j in range(n):
        for k in range(n):
            result_list[i][j] += matrix1[i][k] + matrix2[k][j]

end_time = time.time()
print("Time taken for Python list Matrix Multiplication", end_time - start_time , "seconds")

arr1 = np.random.randint(0, 10, size=(n,n))
arr2 = np.random.randint(0, 10, size=(n,n))

start_time = time.time()
result_np = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for Numpy Array Matrix Multiplication", end_time - start_time , "seconds")


Time taken for Python list Matrix Multiplication 91.84588408470154 seconds
Time taken for Numpy Array Matrix Multiplication 0.45597267150878906 seconds
